services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "400:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: laravel_phpmyadmin
  #   ports:
  #   - "8081:80"
  #   environment:
  #     PMA_HOST: db
  #     PMA_USER: user
  #     PMA_PASSWORD: userpassword
  #   depends_on:
  #   - db

volumes:
  dbdata:
